### PR TITLE
chore(deps): electron@11, latest others

### PR DESCRIPTION
**Pull request by AviVahl**
- reformatted lib using latest prettier.
- added missing awaits to tests.
- removed unused tslint and deprecated (no longer needed) eslint-plugin-standard.

### CODE REVIEW

**Comment by AviVahl** [comment]
the `no-node-integration-test.js` leaves its electron process open. this causes the tests to stay open on Windows.
I tried debugging, but between the chrome driver, child process, remote, and other abstractions, I got a little lost.

I did ensure the isMinimized test works locally. It didn't without the waitUntil, as `minimize()`'s Promise resolves before `isMinimized()` is true. xvfb-based CI still doesn't seem to support isMinimized.

**Comment by AviVahl** [comment]
TBH, I'm uncertain what's causing the tests to stay open on Windows. If someone has a Windows machine and can take a look, it would be useful. Using Fedora 33 here (which is where I saw the `isMinimized()` test failing locally).

**Comment by kevinlinv** [comment]
Same problem with the previous attempt made by @VerteDinde 
https://github.com/electron-userland/spectron/pull/766#issuecomment-731332418

**Comment by VerteDinde** [comment]
@kevinlinv Glad to get some help with debugging! 😄 I'm also having trouble nailing down what's keeping the tests open on Windows. Just kicked a version that fixes an issue with loading `remote.screen` that was causing another test to fail, will let you know what I find

Appreciate you taking the time to update all of our deps - once we figure out what's causing the Windows tests to fail, I'll close my PR and we can merge yours 🙂

**Comment by AviVahl** [comment]
Awesome. I've also installed Windows 10 in a virtualized container trying to see if I can reproduce.
Also rebased branch adding many missing `await` in tests.

**Review by VerteDinde — APPROVED** [review]
Cannot thank you enough for fixing the Windows test issue!

**Comment by AviVahl** [comment]
Happy to help. I did encounter https://github.com/electron-userland/spectron/issues/751 once, so there might be flakiness somewhere there.

I would also like to revert the skipped test on Windows.

**Comment by VerteDinde** [comment]
@AviVahl Sounds great - I'll wait for that revert commit and then will merge when all checks pass 🙂 Thanks again!

**Comment by AviVahl** [comment]
After I reverted, the Windows tests got stuck again. I'll re-add the skip to verify this is the cause this time.
It does feel like the awaits helped things further though.

**Comment by AviVahl** [comment]
Travis is taking forever. I'm guessing you're already aware.

I think there's a good chance Linux container using GitHub actions might work now. The failure I saw the last time I tried (one of the rebases here) was at exactly a point of some of the missing awaits.

**Comment by VerteDinde** [comment]
@AviVahl I restarted Travis, but we might be a victim of us-east-1 delaying builds 😅 I'll keep an eye on this PR and merge once it's passed, so you don't have to babysit it. Thanks so much again for the PR!

**Comment by kevinlinv** [comment]
🎉 Thanks so much for the work here guys!

**Pull request merged**
