### PR TITLE
Upgrade for Electron v6 support

### PR DESCRIPTION
**Pull request by npezza93**

### CODE REVIEW

**Comment by evertonfraga** [comment]
did you run into a specific problem with electron 6? 

mind that the latest two major Spectron versions only had minor changes, so it should work.

**Comment by vladimiry** [comment]
@npezza93 can you actualize the electron and electron-chromedriver versions?

**Comment by npezza93** [comment]
@vladimiry Should be good to go now!

**Comment by vladimiry** [comment]
@codebytere anything blocking the merge?

**Comment by codebytere** [comment]
@vladimiry ty for the ping, i don't think so! i'll draft a new release and get this out the door as soon as i can :)

**Comment by codebytere** [comment]
Done: https://www.npmjs.com/package/spectron/v/8.0.0

**Pull request merged**
