### PR TITLE
test(ci): use github actions Linux container

### PR DESCRIPTION
**Pull request by AviVahl**
the real issue here was xvfb defaulting to a 640x480 screen.

with the electron@11 fixes now in `master`, this might actually pass.
dropped Travis and updated README's badge.

closes #719

### CODE REVIEW

**Comment by AviVahl** [comment]
lets see how it goes... :)

**Comment by AviVahl** [comment]
yay.

**Comment by AviVahl** [comment]
heya @VerteDinde any change you can review this? I believe it will make CI a bit more stable for other PRs.

**Comment by VerteDinde** [comment]
@AviVahl Taking a look now (sorry, was off for the holiday weekend here)! Thanks for doing this!

**Review by jkleinsc — APPROVED** [review]

**Comment by VerteDinde** [comment]
@AviVahl Working awesome, the changes look great 🙇‍♀️

**Comment by AviVahl** [comment]
Thank you both. :)

**Comment by AviVahl** [comment]
Looking at the merge run on `master`, the Windows CI test run still feels flaky (in that it gets stuck).
The Linux run, on the other end, now takes ~2mins and finishes first.

**Pull request merged**
